Repository DanWortho1996/dog-final-project-fe, pull requests merged in 2024-10, with the labels that each got.

#1 chore: setup sanatize
  package-lock.json
  package.json
  public/vite.svg
  src/App.css
  src/App.jsx
  src/assets/react.svg
  src/index.css
Labels: chore

#2 Fodlers setup dw
  src/components/.gitkeep
  src/components/logOrSign/LogOrSign.css
  src/components/logOrSign/LogOrSign.jsx
  src/components/logOrSign/login/Login.css
  src/components/logOrSign/login/Login.jsx
  src/components/logOrSign/signup/Signup.css
  src/components/logOrSign/signup/Signup.jsx
  src/components/menuContainer/MenuContainer.css
  src/components/menuContainer/MenuContainer.jsx
  src/components/profileContainer/ProfileContainer.css
  src/components/profileContainer/ProfileContainer.jsx
  src/components/userListContainer/UserListContainer.css
  src/components/userListContainer/UserListContainer.jsx
  src/pages/landingPage/LandingPage.css
  src/pages/landingPage/LandingPage.jsx
  src/pages/menuPage/MenuPage.css
  src/pages/menuPage/MenuPage.jsx
  src/pages/profilePage/ProfilePage.css
  src/pages/profilePage/ProfilePage.jsx
  src/pages/userListPage/UserListPage.css
  src/pages/userListPage/UserListPage.jsx
  src/utils/fetch.js
Labels: chore

#3 chore: add header & footer folders, files
  src/components/footer/Footer.css
  src/components/footer/Footer.jsx
  src/components/header/Header.css
  src/components/header/Header.jsx
Labels: chore

#4 H and F layout
  src/components/header/Header.jsx
Labels: chore

#6 enhancement: header
  src/components/header/Header.jsx
Labels: enhancement

#8 chore: add userListContainer function
  src/components/userListContainer/UserListContainer.jsx
Labels: chore

#9 enhancement: added css to inner userListContainer
  src/components/userListContainer/UserListContainer.css
Labels: enhancement

#11 Images
  src/App.jsx
  src/components/footer/Footer.jsx
  src/components/header/Header.css
  src/components/header/Header.jsx
  src/components/images/logo1.png
Labels: chore

#12 enhancement: header, footer and app
  src/App.jsx
  src/components/footer/Footer.jsx
  src/components/header/Header.css
  src/components/header/Header.jsx
Labels: enhancement

#14 bug-fix: display visual logo
  src/App.jsx
  src/components/footer/Footer.jsx
Labels: bug

#15 chore: layout folder added
  src/components/header/Header.css
  src/components/layout/Layout.css
  src/components/layout/Layout.jsx
Labels: chore

#17 bug: fix
  src/App.jsx
Labels: bug

#18 Update profile page kr
  src/App.jsx
  src/components/profileContainer/updateProfile/UpdateProfile.css
  src/components/profileContainer/updateProfile/UpdateProfile.jsx
Labels: enhancement

#19 Header and footer bug fix
  src/components/footer/Footer.css
  src/components/footer/Footer.jsx
  src/components/header/Header.css
  src/components/header/Header.jsx
  src/components/images/home.png
  src/components/images/images.png
Labels: enhancement

#24 image folder move
  images/1.png
  images/2.png
  images/home.png
  images/images.png
  images/logo1.png
  src/components/header/Header.jsx
Labels: chore

#25 chore: login form
  src/components/logOrSign/login/Login.jsx
Labels: chore

#27 logout added
  src/App.jsx
  src/components/header/Header.css
  src/components/header/Header.jsx
Labels: chore

#28 Logout debug
  src/App.jsx
  src/components/header/Header.jsx
Labels: enhancement

#29 chore: add MenuPage Buttons, incomplete
  src/pages/menuPage/MenuPage.css
  src/pages/menuPage/MenuPage.jsx
Labels: chore

#30 Fetch fe dw
  src/App.jsx
  src/components/userListContainer/UserListContainer.jsx
  src/pages/menuPage/MenuPage.jsx
  src/pages/userListPage/UserListPage.jsx
  src/utils/fetch.js
Labels: chore

#32 Netlify dw
  src/App.jsx
  src/components/userListContainer/UserListContainer.jsx
  src/pages/landingPage/LandingPage.jsx
  src/utils/fetch.js
Labels: chore

#34 chore: Outlet / Link
  src/components/layout/Layout.jsx
  src/components/userListContainer/UserListContainer.jsx
  src/pages/landingPage/LandingPage.jsx
Labels: chore

#36 chore: bug-fix, netlify
  src/components/layout/Layout.jsx
  src/pages/landingPage/LandingPage.jsx
Labels: chore

#37 chore: more buggys bugs
  src/App.jsx
  src/components/layout/Layout.jsx
  src/pages/landingPage/LandingPage.jsx
  src/pages/profilePage/ProfilePage.jsx
Labels: bug

#39 bug: routes on netlify
  src/App.jsx
  src/pages/dogEventPage/DogEventsPage.jsx
  src/pages/menuPage/MenuPage.jsx
Labels: bug

#41 Profile page setup sw
  src/components/profileContainer/ProfileContainer.jsx
  src/components/profileContainer/profileDelete/ProfileDelete.jsx
  src/components/profileContainer/profileDisplay/ProfileDisplay.jsx
  src/pages/profilePage/ProfilePage.jsx
  src/pages/userListPage/UserListPage.jsx
Labels: chore

#42 Quick fix css dw
  src/components/header/Header.css
  src/components/layout/Layout.css
  src/pages/menuPage/MenuPage.css
  src/pages/menuPage/MenuPage.jsx
Labels: enhancement

#46 Profiledelete sw
  package-lock.json
  package.json
  src/App.jsx
  src/components/profileContainer/ProfileContainer.jsx
  src/components/profileContainer/profileDelete/ProfileDelete.css
  src/components/profileContainer/profileDelete/ProfileDelete.jsx
  src/pages/landingPage/LandingPage.jsx
  src/pages/profilePage/ProfilePage.jsx
  src/utils/fetch.js
Labels: enhancement

#47 update: changed cors
  src/App.jsx
  src/utils/fetch.js
Labels: chore

#51 enhancement: logo changed
  images/one.png
  src/components/header/Header.css
  src/components/header/Header.jsx
Labels: enhancement

#52 logout button debugged
  src/components/header/Header.jsx
  src/pages/profilePage/ProfilePage.css
  src/pages/profilePage/ProfilePage.jsx
Labels: enhancement

#53 enhancement: profilePage shows details once user logged in, however n…
  src/pages/profilePage/ProfilePage.jsx
Labels: enhancement

#55 Dog id fe dw
  src/components/userListContainer/UserListContainer.jsx
  src/pages/userListPage/UserListPage.jsx
Labels: bug

#57 enhancmenet: styling for allUsers
  src/components/userListContainer/UserListContainer.css
  src/components/userListContainer/UserListContainer.jsx
Labels: documentation, enhancement

#59 enhancement: google maps
  package-lock.json
  package.json
  src/components/userListContainer/UserListContainer.jsx
Labels: enhancement

#61 enhancement: active users and maps
  src/components/userListContainer/UserListContainer.css
Labels: enhancement

#62 enahcement: menu button back to menu from each page
  src/components/header/Header.jsx
  src/components/profileContainer/ProfileContainer.jsx
Labels: chore
